- name: setup grafana (docker)
  hosts: all
  become: true
  vars:
    grafana_domain: "{{ domain }}"
    grafana_workspace: /opt/grafana
    grafana_admin_user: admin
    grafana_admin_password: admin
  roles:
    - vhosts/docker/
    - docker/grafana/
